		;MAIN	FUNCTION
MAIN
		;INITIALIZE	R0 AND R1
		MOV		R0,#9
		MOV		R1,#8
		;CALL	SORT FUNCTION
		BL		SORT
		END
SORT
		;STORE	LR AND R2-R4 IN STACK
		STMFD	R13!,{LR}
		STMFD	R13!,{R2-R4}
		;		SORT R0 AND R1
		CMP		R0,R1
		BLE		DONE
		MOV		R2,R0
		MOV		R0,R1
		MOV		R1,R2
DONE
		;LOAD	LR AND R2-R4 FROM STACK
		LDMFD	R13!,{R2-R4}
		LDMFD	R13!,{LR}
		;		RETURN TO MAIN FUNCTION
		MOV		PC,LR
