		;MAIN	FUNCTION
MAIN
		;		STORE NUMBERS IN STACK
		LDR		R0,=123
		STMFD	R13!,{R0}
		LDR		R0,=12
		STMFD	R13!,{R0}
		LDR		R0,=45
		STMFD	R13!,{R0}
		LDR		R0,=87
		STMFD	R13!,{R0}
		LDR		R0,=233
		STMFD	R13!,{R0}
		;		STORE n IN STACK
		LDR		R0,=5
		STMFD	R13!,{R0}
		;		CALL FUNCTION
		BL		FUNC
		;		LOAD MIN AND MAX IN R10 AND R11
		LDMFD	R13!,{R11}
		LDMFD	R13!,{R10}
		END
		;FUNCTION	TO CALCULATE MIN AND MAX
FUNC
		;LOAD	N IN R0
		LDMFD	R13!,{R0}
		
		;SET		FIRST NUMBER TO MIN AND MAX
		LDMFD	R13!,{R1}
		SUB		R0,R0,#1
		MOV		R8,R1	;R8 -> MAX
		MOV		R9,R1	;R9 -> MIN
		
CALC
		LDMFD	R13!,{R1}
		SUB		R0,R0,#1
		
		;CALCULATE	MAX
		CMP		R1,R8
		BLS		LESS
		MOV		R8,R1
LESS
		
		;CALCULATE	MIN
		CMP		R1,R9
		BHS		HIGH
		MOV		R9,R1
HIGH
		
		CMP		R0,#0
		BNE		CALC
		
		;STORE	MIN AND MAX IN STACK
		STMFD	R13!,{R8,R9}
		;RETURN	TO MAIN
		MOV		PC,LR
		
